package com.skin.management.mapper;

import com.skin.management.entity.AdminMenu;
import com.skin.management.entity.AdminMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    long countByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int deleteByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int insert(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int insertSelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    List<AdminMenu> selectByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    AdminMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminMenu record, @Param("example") AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminMenu record, @Param("example") AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminMenu record);
}